package net.kaciras.blog.api.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.kaciras.blog.api.ConvertorRegistery;
import net.kaciras.blog.infrastructure.event.ConfigChangedEvent;
import net.kaciras.blog.infrastructure.exception.RequestArgumentException;
import net.kaciras.blog.infrastructure.message.MessageClient;
import org.dom4j.DocumentException;
import org.dom4j.io.SAXReader;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import java.io.*;
import java.util.Map;
import java.util.Properties;

@Slf4j
@RequiredArgsConstructor
@Service
public class ConfigService {

	private final MessageClient messageClient;
	private final ConfigurableEnvironment environment;
	private final ConvertorRegistery convertorRegistery;

	private Properties properties;
	private Map<String, PropertyGroup> configurables;

	@SuppressWarnings("ConstantConditions")
	@PostConstruct
	private void loadModifiable() throws IOException, DocumentException {
		InputStream stream = ConfigService.class.getClassLoader().getResourceAsStream("configurable.xml");
		try (stream) {
			ConfigurableElementHandler handler = new ConfigurableElementHandler();
			SAXReader saxReader = new SAXReader();
			saxReader.setEncoding("UTF-8");
			saxReader.setDefaultHandler(handler);
			saxReader.read(stream);
			configurables = handler.getConfigurables();
		}
		properties = (Properties) environment.getPropertySources().get("ConfigServiceSource").getSource();
	}

	@PreDestroy
	private void saveProperties() throws IOException {
		new File("data").mkdirs();
		try (OutputStream out = new FileOutputStream("data/config.properties")){
			properties.store(out, "This file is generated by Config Service.");
		}
	}

	public String getProperty(String key) {
		return environment.getProperty(key);
	}

	public void set(String key, String value) {
		/* 检查配置项的值是否符合定义的类型 */
		String[] tupe = key.split("\\.", 2);
		PropertyItem item = configurables.get(tupe[0]).getItems().get(tupe[1]);
		if(!convertorRegistery.checkType(item.getType(), value)) {
			throw new RequestArgumentException("配置项的值不符合定义的类型");
		}

		logger.trace("put config: {} = {}", key, value);
		properties.put(key,value);
		messageClient.send(new ConfigChangedEvent(key, properties.getProperty(key), value));
	}

	public Map<String, PropertyGroup> getModifiable() {
		return configurables;
	}
}
